// below is our first js code to test whether js is linked appropriately and is working well as well

//alert("Welcome to the Welcome page!")

// Selecting an entire form by ID name...
const registerForm = document.getElementById('register-form'); // note that "const" can be replaced by "let" in this case...

// handling our form's SubmitEvent...
registerForm.onsubmit = function() {
    // collect user name...
    // collect email...
    // collect password...
    // save user info...
    // send configuration email...
}